version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "lambda-extension-dev"
s3_bucket = "pyroscope-lambda-extension-dev"
s3_prefix = ""
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

