name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: asdf_install
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2
      - run: make install-dev-tools
      # Make asdf aware of globally installed binaries
      - run: asdf reshim

      - run: make test
      - run: make lint
      - if: ${{ matrix.architecture == 'arm64' }}
        run: make build-arm
      - if: ${{ matrix.architecture == 'amd64' }}
        run: make build-amd

  check-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: asdf_install
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2
      - run: make shellcheck
