name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: 'false'
      - name: asdf_install
        uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4.0.0
      - run: make install-dev-tools
      # Make asdf aware of globally installed binaries
      - run: asdf reshim

      - run: make test
      - run: make lint
      - if: ${{ matrix.architecture == 'arm64' }}
        run: make build-arm
      - if: ${{ matrix.architecture == 'amd64' }}
        run: make build-amd

  check-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: 'false'
      - name: asdf_install
        uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4.0.0
      - run: make shellcheck
