# We need to lint commits since they are used to generate changelogs
name: Lint Commit Messages

# The only commit we care about is the one to main
# Since that's the one used to generate the changelog
on:
  push:
    branches: [main]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [amd64]
    steps:
      - uses: actions/checkout@v3
        with:
          # Required since we fetch a list of commits
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
