on:
  push:
    branches:
      - main

permissions:
  contents: read

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      release_created: ${{ steps.rp.outputs.release_created }}
      tag_name: ${{ steps.rp.outputs.tag_name }}
      sha: ${{ steps.rp.outputs.sha }}
    steps:
      - id: get-github-app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@ae92934a14a48b94494dbc06d74a81d47fe08a40 # create-github-app-token/v0.2.2
        with:
          github_app: pyroscope-development-app
      - id: rp
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        with:
          token: ${{ steps.get-github-app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
